# Generated by Django 2.0.4 on 2018-05-03 15:51

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180502_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='Content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
