# Generated by Django 2.0.4 on 2018-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180503_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='总数'),
        ),
        migrations.AddField(
            model_name='tag',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='总数'),
        ),
    ]
